# Generated by Django 5.2.17 on 2026-08-22 23:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleNumberCounter',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'sale number counter',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reversed', 'Reversed')], db_index=True, default='completed', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='discount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cost_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('bank', 'Bank Transfer')], default='cash', max_length=10, verbose_name='payment method')),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='amount received')),
                ('change_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Optional. Mobile Money or bank transaction reference.', max_length=60, verbose_name='payment reference')),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=300)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reversed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=140)),
                ('sku', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-completed_at', 'status'], name='sale_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_method'], name='sale_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', Decimal('0')), ('discount__gte', Decimal('0'))), name='sale_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('subtotal'))), name='sale_discount_within_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='saleitem_qty_positive'),
        ),
    ]
