# Generated by Django 5.2.17 on 2026-08-22 23:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='JCF Organic', max_length=120, verbose_name='shop name')),
                ('tagline', models.CharField(blank=True, default='Natural & organic goods', max_length=160, verbose_name='tagline')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('address', models.TextField(blank=True, verbose_name='shop address')),
                ('receipt_footer', models.CharField(blank=True, default='Thank you for shopping with us!', max_length=200, verbose_name='receipt footer message')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Used for new products that do not set their own level.', verbose_name='default low-stock level')),
                ('expiry_warning_days', models.PositiveIntegerField(default=30, help_text='Products expiring within this many days are flagged as expiring soon.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='expiry warning period (days)')),
                ('large_adjustment_threshold', models.DecimalField(decimal_places=3, default=Decimal('20'), help_text='Adjustments at or above this quantity ask for extra confirmation.', max_digits=12, verbose_name='large adjustment size')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shop settings',
                'verbose_name_plural': 'shop settings',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login', 'Signed in'), ('login_failed', 'Failed sign-in attempt'), ('logout', 'Signed out'), ('product_created', 'Product created'), ('product_updated', 'Product updated'), ('product_status_changed', 'Product activated/deactivated'), ('category_created', 'Category created'), ('category_updated', 'Category updated'), ('supplier_created', 'Supplier created'), ('supplier_updated', 'Supplier updated'), ('opening_stock', 'Opening stock recorded'), ('stock_received', 'Stock received'), ('stock_adjusted', 'Stock adjusted'), ('sale_completed', 'Sale completed'), ('sale_reversed', 'Sale reversed'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_status_changed', 'User activated/deactivated'), ('password_reset', 'Password reset by owner'), ('settings_updated', 'Shop settings updated'), ('data_exported', 'Data exported')], db_index=True, max_length=40)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('object_label', models.CharField(blank=True, max_length=200)),
                ('summary', models.CharField(max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_object_idx'), models.Index(fields=['-created_at', 'action'], name='audit_recent_idx')],
            },
        ),
    ]
