# Generated by Django 5.2.17 on 2026-08-22 23:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('opening', 'Opening stock'), ('received', 'Stock received'), ('return', 'Customer return'), ('correction', 'Stock correction')], default='received', max_length=16)),
                ('batch_number', models.CharField(blank=True, help_text='Optional. The batch or lot code printed on the packaging.', max_length=60, verbose_name='batch number')),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantity')),
                ('quantity_remaining', models.DecimalField(decimal_places=3, editable=False, max_digits=14, verbose_name='quantity remaining')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='What you paid for one unit in this delivery.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='unit cost')),
                ('expiry_date', models.DateField(blank=True, help_text='Leave empty for products that do not expire.', null=True, verbose_name='expiry date')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date received')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'stock batch',
                'verbose_name_plural': 'stock batches',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Opening stock'), ('received', 'Stock received'), ('sale', 'Sale'), ('sale_reversal', 'Sale reversed'), ('return', 'Customer return'), ('damaged', 'Damaged stock'), ('expired', 'Expired stock'), ('missing', 'Missing stock'), ('correction_up', 'Positive correction'), ('correction_down', 'Negative correction')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at the moment of the movement.', max_digits=12, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='sales.sale')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='sales.saleitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stock movement',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'expiry_date'], name='batch_prod_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='batch_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__gte', Decimal('0'))), name='batch_remaining_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__lte', models.F('quantity_received'))), name='batch_remaining_within_received'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='movement_product_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at', 'movement_type'], name='movement_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', Decimal('0')), _negated=True), name='movement_quantity_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gte', Decimal('0'))), name='movement_after_not_negative'),
        ),
    ]
