# Generated by Django 5.2.17 on 2026-08-22 23:31

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=80, verbose_name='category name')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=120, verbose_name='supplier name')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Enter a valid phone number, for example 024 123 4567 or +233 24 123 4567.')], verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location or address')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='supplier_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=140, verbose_name='product name')),
                ('sku', models.CharField(help_text='A short unique code you use to identify this product, e.g. HON-500.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9\\-_/]{1,31}$', 'Use letters, numbers, dashes or slashes (2–32 characters).')], verbose_name='SKU / product code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('bottle', 'Bottle'), ('pack', 'Pack'), ('sachet', 'Sachet'), ('box', 'Box'), ('bag', 'Bag'), ('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Millilitre (ml)'), ('l', 'Litre (L)')], default='piece', max_length=10, verbose_name='unit of measurement')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='What you normally pay your supplier for one unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cost price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='What the customer pays for one unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='selling price')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('5'), help_text='Warn me when stock falls to this level or below.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='low-stock level')),
                ('barcode', models.CharField(blank=True, help_text='Optional. Scan or type the barcode printed on the product.', max_length=64, verbose_name='barcode')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14, verbose_name='stock on hand')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products are hidden from the sales screen but keep their history.', verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='product_active_name_idx'), models.Index(fields=['stock_quantity'], name='product_stock_idx'), models.Index(fields=['barcode'], name='product_barcode_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stock_quantity__gte', Decimal('0'))), name='product_stock_not_negative'), models.CheckConstraint(condition=models.Q(('selling_price__gte', Decimal('0')), ('cost_price__gte', Decimal('0'))), name='product_prices_not_negative'), models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), name='product_sku_unique_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('barcode'), condition=models.Q(('barcode', ''), _negated=True), name='product_barcode_unique_ci')],
            },
        ),
    ]
