# Generated by Django 5.2.17 on 2026-08-23 13:42

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_sku_unique_ci',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Optional. A short code you use to identify this product, e.g. HON-500. It makes searching at the till faster, and must be unique if you use one.', max_length=32, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9\\-_/]{1,31}$', 'Use letters, numbers, dashes or slashes (2–32 characters).')], verbose_name='SKU / product code'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), condition=models.Q(('sku', ''), _negated=True), name='product_sku_unique_ci'),
        ),
    ]
